[package]
name = "vessel"
version = "0.1.0"
authors = ["kritzcreek <christoph.hegemann1337@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
log = "0.4"
pretty_env_logger = "0.4"
tar = "0.4"
flate2 = "1"
reqwest = { version = "0.10", features = ["blocking"] }
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
anyhow = "1.0"
